version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bike_rental
      - POSTGRES_USER=bike_rental
      - POSTGRES_PASSWORD=bike_rental
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:.
    environment:
      - DJANGO_SETTINGS_MODULE=bike_rental.settings
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: